# Generated by Django 5.1.2 on 2024-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_application_job_question_requiredskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='App_id',
            field=models.IntegerField(default=-1),
        ),
    ]
